// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kerneldl_exp_generic_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        x,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [63:0] x;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_state30_pp0_stage0_iter29;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0;
reg    table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0;
wire   [57:0] table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
wire   [7:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0;
reg    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0;
wire   [25:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
wire   [7:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1;
reg    table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1;
wire   [25:0] table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1;
wire   [7:0] table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0;
reg    table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0;
wire   [41:0] table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
wire   [0:0] p_Result_275_fu_265_p3;
reg   [0:0] p_Result_275_reg_1135;
reg   [0:0] p_Result_275_reg_1135_pp0_iter1_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter2_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter3_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter4_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter5_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter6_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter7_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter8_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter9_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter10_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter11_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter12_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter13_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter14_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter15_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter16_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter17_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter18_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter19_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter20_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter21_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter22_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter23_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter24_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter25_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter26_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter27_reg;
reg   [0:0] p_Result_275_reg_1135_pp0_iter28_reg;
wire   [0:0] and_ln209_fu_299_p2;
reg   [0:0] and_ln209_reg_1140;
reg   [0:0] and_ln209_reg_1140_pp0_iter1_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter2_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter3_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter4_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter5_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter6_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter7_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter8_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter9_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter10_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter11_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter12_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter13_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter14_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter15_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter16_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter17_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter18_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter19_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter20_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter21_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter22_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter23_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter24_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter25_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter26_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter27_reg;
reg   [0:0] and_ln209_reg_1140_pp0_iter28_reg;
wire   [0:0] and_ln18_fu_311_p2;
reg   [0:0] and_ln18_reg_1147;
reg   [0:0] and_ln18_reg_1147_pp0_iter1_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter2_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter3_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter4_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter5_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter6_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter7_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter8_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter9_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter10_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter11_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter12_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter13_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter14_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter15_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter16_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter17_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter18_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter19_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter20_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter21_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter22_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter23_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter24_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter25_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter26_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter27_reg;
reg   [0:0] and_ln18_reg_1147_pp0_iter28_reg;
wire   [53:0] select_ln253_fu_341_p3;
reg   [53:0] select_ln253_reg_1153;
reg   [53:0] select_ln253_reg_1153_pp0_iter1_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter2_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter3_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter4_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter5_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter6_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter7_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter8_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter9_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter10_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter11_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter12_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter13_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter14_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter15_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter16_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter17_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter18_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter19_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter20_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter21_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter22_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter23_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter24_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter25_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter26_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter27_reg;
reg   [53:0] select_ln253_reg_1153_pp0_iter28_reg;
wire   [0:0] isNeg_fu_349_p3;
reg   [0:0] isNeg_reg_1159;
wire   [11:0] m_exp_2_fu_367_p3;
reg   [11:0] m_exp_2_reg_1165;
wire   [0:0] icmp_ln338_fu_375_p2;
reg   [0:0] icmp_ln338_reg_1170;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter1_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter2_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter3_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter4_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter5_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter6_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter7_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter8_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter9_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter10_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter11_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter12_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter13_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter14_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter15_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter16_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter17_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter18_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter19_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter20_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter21_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter22_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter23_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter24_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter25_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter26_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter27_reg;
reg   [0:0] icmp_ln338_reg_1170_pp0_iter28_reg;
wire  signed [70:0] r_V_50_fu_419_p3;
reg  signed [70:0] r_V_50_reg_1178;
reg  signed [70:0] r_V_50_reg_1178_pp0_iter2_reg;
reg  signed [70:0] r_V_50_reg_1178_pp0_iter3_reg;
reg  signed [70:0] r_V_50_reg_1178_pp0_iter4_reg;
reg  signed [70:0] r_V_50_reg_1178_pp0_iter5_reg;
reg  signed [70:0] r_V_50_reg_1178_pp0_iter6_reg;
reg  signed [70:0] r_V_50_reg_1178_pp0_iter7_reg;
reg  signed [70:0] r_V_50_reg_1178_pp0_iter8_reg;
reg  signed [70:0] r_V_50_reg_1178_pp0_iter9_reg;
reg   [0:0] p_Result_276_reg_1183;
reg   [0:0] p_Result_276_reg_1183_pp0_iter2_reg;
wire   [0:0] icmp_ln338_1_fu_489_p2;
reg   [0:0] icmp_ln338_1_reg_1193;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter2_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter3_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter4_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter5_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter6_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter7_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter8_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter9_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter10_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter11_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter12_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter13_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter14_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter15_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter16_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter17_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter18_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter19_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter20_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter21_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter22_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter23_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter24_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter25_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter26_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter27_reg;
reg   [0:0] icmp_ln338_1_reg_1193_pp0_iter28_reg;
wire  signed [12:0] r_exp_V_3_fu_545_p3;
reg  signed [12:0] r_exp_V_3_reg_1203;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter5_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter6_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter7_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter8_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter9_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter10_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter11_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter12_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter13_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter14_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter15_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter16_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter17_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter18_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter19_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter20_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter21_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter22_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter23_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter24_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter25_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter26_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter27_reg;
reg  signed [12:0] r_exp_V_3_reg_1203_pp0_iter28_reg;
reg   [70:0] tmp_s_reg_1215;
reg   [7:0] m_diff_hi_V_reg_1220;
reg   [7:0] m_diff_hi_V_reg_1220_pp0_iter11_reg;
reg   [7:0] m_diff_hi_V_reg_1220_pp0_iter12_reg;
reg   [7:0] m_diff_hi_V_reg_1220_pp0_iter13_reg;
reg   [7:0] m_diff_hi_V_reg_1220_pp0_iter14_reg;
reg   [7:0] m_diff_hi_V_reg_1220_pp0_iter15_reg;
reg   [7:0] m_diff_hi_V_reg_1220_pp0_iter16_reg;
reg   [7:0] m_diff_hi_V_reg_1220_pp0_iter17_reg;
reg   [7:0] m_diff_hi_V_reg_1220_pp0_iter18_reg;
reg   [7:0] m_diff_hi_V_reg_1220_pp0_iter19_reg;
reg   [7:0] m_diff_hi_V_reg_1220_pp0_iter20_reg;
reg   [7:0] Z2_V_reg_1225;
reg   [7:0] Z2_V_reg_1225_pp0_iter11_reg;
reg   [7:0] Z2_V_reg_1225_pp0_iter12_reg;
reg   [7:0] Z2_V_reg_1225_pp0_iter13_reg;
reg   [7:0] Z2_V_reg_1225_pp0_iter14_reg;
reg   [7:0] Z2_V_reg_1225_pp0_iter15_reg;
reg   [7:0] Z2_V_reg_1225_pp0_iter16_reg;
reg   [7:0] Z2_V_reg_1225_pp0_iter17_reg;
reg   [7:0] Z2_V_reg_1225_pp0_iter18_reg;
reg   [7:0] Z2_V_reg_1225_pp0_iter19_reg;
reg   [7:0] Z2_V_reg_1225_pp0_iter20_reg;
reg   [7:0] Z2_V_reg_1225_pp0_iter21_reg;
wire   [7:0] Z3_V_fu_612_p4;
reg   [7:0] Z3_V_reg_1232;
reg   [7:0] Z3_V_reg_1232_pp0_iter11_reg;
wire   [34:0] Z4_V_fu_622_p1;
reg   [34:0] Z4_V_reg_1237;
wire   [35:0] ret_V_20_fu_663_p2;
reg   [35:0] ret_V_20_reg_1252;
reg   [35:0] ret_V_20_reg_1252_pp0_iter12_reg;
reg   [35:0] ret_V_20_reg_1252_pp0_iter13_reg;
reg   [35:0] ret_V_20_reg_1252_pp0_iter14_reg;
reg   [35:0] ret_V_20_reg_1252_pp0_iter15_reg;
reg   [25:0] p_Val2_251_reg_1258;
wire   [42:0] tmp_i_fu_669_p4;
reg   [42:0] tmp_i_reg_1263;
reg   [42:0] tmp_i_reg_1263_pp0_iter13_reg;
reg   [42:0] tmp_i_reg_1263_pp0_iter14_reg;
reg   [42:0] tmp_i_reg_1263_pp0_iter15_reg;
reg   [19:0] tmp_76_reg_1278;
wire   [43:0] exp_Z2P_m_1_V_fu_719_p2;
reg   [43:0] exp_Z2P_m_1_V_reg_1288;
reg   [43:0] exp_Z2P_m_1_V_reg_1288_pp0_iter17_reg;
reg   [43:0] exp_Z2P_m_1_V_reg_1288_pp0_iter18_reg;
reg   [43:0] exp_Z2P_m_1_V_reg_1288_pp0_iter19_reg;
reg   [43:0] exp_Z2P_m_1_V_reg_1288_pp0_iter20_reg;
reg   [43:0] exp_Z2P_m_1_V_reg_1288_pp0_iter21_reg;
reg   [39:0] tmp_77_reg_1294;
reg   [39:0] tmp_77_reg_1294_pp0_iter17_reg;
reg   [39:0] tmp_77_reg_1294_pp0_iter18_reg;
reg   [39:0] tmp_77_reg_1294_pp0_iter19_reg;
reg   [39:0] tmp_77_reg_1294_pp0_iter20_reg;
reg   [39:0] tmp_77_reg_1294_pp0_iter21_reg;
reg   [35:0] tmp_78_reg_1315;
reg   [57:0] exp_Z1_V_reg_1320;
reg   [57:0] exp_Z1_V_reg_1320_pp0_iter23_reg;
reg   [57:0] exp_Z1_V_reg_1320_pp0_iter24_reg;
reg   [57:0] exp_Z1_V_reg_1320_pp0_iter25_reg;
reg   [57:0] exp_Z1_V_reg_1320_pp0_iter26_reg;
reg   [57:0] exp_Z1_V_reg_1320_pp0_iter27_reg;
reg   [49:0] exp_Z1P_m_1_V_reg_1325;
reg   [49:0] exp_Z1_hi_V_reg_1330;
wire   [99:0] grp_fu_828_p2;
reg   [99:0] r_V_55_reg_1345;
reg   [99:0] r_V_55_reg_1345_pp0_iter28_reg;
wire   [58:0] ret_V_22_fu_837_p2;
reg   [58:0] ret_V_22_reg_1351;
reg   [0:0] tmp_436_reg_1356;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln498_1_fu_636_p1;
wire   [63:0] zext_ln498_2_fu_641_p1;
wire   [63:0] zext_ln498_3_fu_700_p1;
wire   [63:0] zext_ln498_fu_756_p1;
wire   [63:0] p_Val2_s_fu_261_p1;
wire   [10:0] tmp_V_fu_273_p4;
wire   [51:0] tmp_V_49_fu_283_p1;
wire   [0:0] icmp_ln833_fu_287_p2;
wire   [0:0] icmp_ln837_fu_293_p2;
wire   [0:0] icmp_ln833_3_fu_305_p2;
wire   [11:0] zext_ln502_fu_317_p1;
wire   [53:0] p_Result_s_fu_327_p3;
wire   [53:0] e_frac_V_fu_335_p2;
wire   [11:0] m_exp_fu_321_p2;
wire   [10:0] sub_ln1311_fu_357_p2;
wire  signed [11:0] sext_ln1311_fu_363_p1;
wire  signed [60:0] m_frac_l_V_fu_381_p3;
wire  signed [31:0] sext_ln1311_1_fu_392_p1;
wire   [60:0] zext_ln1285_fu_399_p1;
wire   [60:0] r_V_fu_403_p2;
wire  signed [70:0] sext_ln682_fu_388_p1;
wire   [70:0] zext_ln1287_fu_395_p1;
wire  signed [70:0] sext_ln1287_fu_409_p1;
wire   [70:0] r_V_38_fu_413_p2;
wire   [63:0] m_fix_l_V_fu_426_p4;
wire   [63:0] zext_ln1253_fu_436_p1;
wire  signed [15:0] m_fix_hi_V_fu_452_p4;
wire   [63:0] r_V_40_fu_440_p2;
wire   [63:0] r_V_41_fu_446_p2;
wire   [63:0] select_ln1322_fu_474_p3;
wire   [70:0] shl_ln_fu_481_p3;
wire  signed [18:0] rhs_V_fu_495_p3;
wire  signed [30:0] grp_fu_1124_p3;
wire   [17:0] trunc_ln805_fu_522_p1;
wire   [12:0] tmp_16_fu_506_p4;
wire   [0:0] icmp_ln805_fu_525_p2;
wire   [12:0] add_ln805_fu_531_p2;
wire   [0:0] p_Result_268_fu_515_p3;
wire   [12:0] select_ln805_fu_537_p3;
wire   [71:0] grp_fu_556_p0;
wire   [83:0] grp_fu_556_p2;
wire   [71:0] rhs_V_1_fu_575_p3;
wire  signed [72:0] lhs_V_fu_572_p1;
wire  signed [72:0] sext_ln682_2_fu_582_p1;
wire   [72:0] ret_V_19_fu_586_p2;
wire   [7:0] Z4_ind_V_fu_626_p4;
wire   [9:0] f_Z4_V_fu_646_p4;
wire   [35:0] rhs_V_5_fu_659_p1;
wire   [35:0] lhs_V_15_fu_656_p1;
wire   [35:0] grp_fu_684_p0;
wire   [42:0] grp_fu_684_p1;
wire   [78:0] grp_fu_684_p2;
wire   [35:0] zext_ln657_fu_707_p1;
wire   [35:0] add_ln657_fu_710_p2;
wire   [43:0] ret_V_21_fu_704_p1;
wire   [43:0] zext_ln657_1_fu_715_p1;
wire   [48:0] lshr_ln662_6_fu_735_p4;
wire   [43:0] grp_fu_750_p0;
wire   [48:0] grp_fu_750_p1;
wire   [92:0] grp_fu_750_p2;
wire   [50:0] lhs_V_4_fu_770_p5;
wire   [43:0] zext_ln657_2_fu_784_p1;
wire   [43:0] add_ln657_2_fu_787_p2;
wire   [51:0] zext_ln682_fu_780_p1;
wire   [51:0] zext_ln657_3_fu_792_p1;
wire   [51:0] exp_Z1P_m_1_l_V_fu_796_p2;
wire   [49:0] grp_fu_828_p0;
wire   [49:0] grp_fu_828_p1;
wire   [58:0] lhs_V_16_fu_834_p1;
wire   [57:0] trunc_ln1146_fu_846_p1;
wire   [106:0] trunc_ln_fu_850_p3;
wire   [106:0] zext_ln1146_fu_843_p1;
wire   [106:0] add_ln1146_1_fu_858_p2;
wire   [0:0] xor_ln936_fu_872_p2;
wire   [0:0] x_is_pinf_fu_877_p2;
wire   [0:0] or_ln214_fu_882_p2;
wire   [63:0] select_ln214_fu_887_p3;
wire   [107:0] zext_ln657_5_fu_913_p1;
wire   [107:0] lhs_V_6_fu_906_p3;
wire   [12:0] r_exp_V_fu_922_p2;
wire   [12:0] r_exp_V_2_fu_927_p3;
wire   [2:0] tmp_437_fu_933_p4;
wire   [0:0] icmp_ln849_fu_943_p2;
wire   [0:0] tmp_438_fu_954_p3;
wire   [107:0] ret_V_23_fu_916_p2;
wire   [51:0] tmp_fu_975_p4;
wire   [51:0] tmp_17_fu_985_p4;
wire   [10:0] trunc_ln168_fu_1002_p1;
wire   [10:0] out_exp_V_fu_1006_p2;
wire   [51:0] tmp_V_50_fu_995_p3;
wire   [63:0] p_Result_277_fu_1012_p4;
wire   [0:0] or_ln214_1_fu_894_p2;
wire   [0:0] or_ln338_fu_949_p2;
wire   [0:0] xor_ln338_fu_1037_p2;
wire   [0:0] and_ln338_fu_1032_p2;
wire   [0:0] and_ln849_fu_1042_p2;
wire   [0:0] or_ln849_fu_1048_p2;
wire   [0:0] xor_ln214_fu_1026_p2;
wire   [0:0] sel_tmp5_fu_1054_p2;
wire   [63:0] select_ln339_fu_961_p3;
wire   [63:0] bitcast_ln512_fu_1022_p1;
wire   [63:0] select_ln214_1_fu_898_p3;
wire   [63:0] sel_tmp6_fu_1060_p3;
wire   [0:0] xor_ln338_1_fu_1076_p2;
wire   [0:0] or_ln849_1_fu_1087_p2;
wire   [0:0] and_ln338_1_fu_1082_p2;
wire   [0:0] xor_ln849_fu_1092_p2;
wire   [0:0] or_ln849_2_fu_1098_p2;
wire   [0:0] tmp19_fu_1104_p2;
wire   [0:0] icmp_ln853_fu_969_p2;
wire   [0:0] sel_tmp16_fu_1110_p2;
wire   [63:0] select_ln214_2_fu_1068_p3;
wire   [15:0] grp_fu_1124_p0;
reg    grp_fu_556_ce;
reg    grp_fu_684_ce;
reg    grp_fu_750_ce;
reg    grp_fu_828_ce;
reg    grp_fu_1124_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to28;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [78:0] grp_fu_684_p00;
wire   [78:0] grp_fu_684_p10;
wire   [92:0] grp_fu_750_p00;
wire   [92:0] grp_fu_750_p10;
wire   [99:0] grp_fu_828_p00;
wire   [99:0] grp_fu_828_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
end

kerneldl_exp_generic_double_s_table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_arbkb #(
    .DataWidth( 58 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0),
    .ce0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0),
    .q0(table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0)
);

kerneldl_exp_generic_double_s_table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arracud #(
    .DataWidth( 26 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0),
    .ce0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0),
    .q0(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0),
    .address1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1),
    .ce1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1),
    .q1(table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1)
);

kerneldl_exp_generic_double_s_table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_arradEe #(
    .DataWidth( 42 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0),
    .ce0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0),
    .q0(table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0)
);

kerneldl_kerneldl_mul_72ns_13s_84_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 72 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 84 ))
kerneldl_mul_72ns_13s_84_5_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_556_p0),
    .din1(r_exp_V_3_reg_1203),
    .ce(grp_fu_556_ce),
    .dout(grp_fu_556_p2)
);

kerneldl_kerneldl_mul_36ns_43ns_79_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 36 ),
    .din1_WIDTH( 43 ),
    .dout_WIDTH( 79 ))
kerneldl_mul_36ns_43ns_79_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_684_p0),
    .din1(grp_fu_684_p1),
    .ce(grp_fu_684_ce),
    .dout(grp_fu_684_p2)
);

kerneldl_kerneldl_mul_44ns_49ns_93_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 44 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 93 ))
kerneldl_mul_44ns_49ns_93_5_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_750_p0),
    .din1(grp_fu_750_p1),
    .ce(grp_fu_750_ce),
    .dout(grp_fu_750_p2)
);

kerneldl_kerneldl_mul_50ns_50ns_100_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 100 ))
kerneldl_mul_50ns_50ns_100_5_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_828_p0),
    .din1(grp_fu_828_p1),
    .ce(grp_fu_828_ce),
    .dout(grp_fu_828_p2)
);

kerneldl_kerneldl_mac_muladd_16ns_16s_19s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 31 ))
kerneldl_mac_muladd_16ns_16s_19s_31_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1124_p0),
    .din1(m_fix_hi_V_fu_452_p4),
    .din2(rhs_V_fu_495_p3),
    .ce(grp_fu_1124_ce),
    .dout(grp_fu_1124_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Z2_V_reg_1225 <= {{ret_V_19_fu_586_p2[50:43]}};
        Z2_V_reg_1225_pp0_iter11_reg <= Z2_V_reg_1225;
        Z2_V_reg_1225_pp0_iter12_reg <= Z2_V_reg_1225_pp0_iter11_reg;
        Z2_V_reg_1225_pp0_iter13_reg <= Z2_V_reg_1225_pp0_iter12_reg;
        Z2_V_reg_1225_pp0_iter14_reg <= Z2_V_reg_1225_pp0_iter13_reg;
        Z2_V_reg_1225_pp0_iter15_reg <= Z2_V_reg_1225_pp0_iter14_reg;
        Z2_V_reg_1225_pp0_iter16_reg <= Z2_V_reg_1225_pp0_iter15_reg;
        Z2_V_reg_1225_pp0_iter17_reg <= Z2_V_reg_1225_pp0_iter16_reg;
        Z2_V_reg_1225_pp0_iter18_reg <= Z2_V_reg_1225_pp0_iter17_reg;
        Z2_V_reg_1225_pp0_iter19_reg <= Z2_V_reg_1225_pp0_iter18_reg;
        Z2_V_reg_1225_pp0_iter20_reg <= Z2_V_reg_1225_pp0_iter19_reg;
        Z2_V_reg_1225_pp0_iter21_reg <= Z2_V_reg_1225_pp0_iter20_reg;
        Z3_V_reg_1232 <= {{ret_V_19_fu_586_p2[42:35]}};
        Z3_V_reg_1232_pp0_iter11_reg <= Z3_V_reg_1232;
        Z4_V_reg_1237 <= Z4_V_fu_622_p1;
        and_ln18_reg_1147_pp0_iter10_reg <= and_ln18_reg_1147_pp0_iter9_reg;
        and_ln18_reg_1147_pp0_iter11_reg <= and_ln18_reg_1147_pp0_iter10_reg;
        and_ln18_reg_1147_pp0_iter12_reg <= and_ln18_reg_1147_pp0_iter11_reg;
        and_ln18_reg_1147_pp0_iter13_reg <= and_ln18_reg_1147_pp0_iter12_reg;
        and_ln18_reg_1147_pp0_iter14_reg <= and_ln18_reg_1147_pp0_iter13_reg;
        and_ln18_reg_1147_pp0_iter15_reg <= and_ln18_reg_1147_pp0_iter14_reg;
        and_ln18_reg_1147_pp0_iter16_reg <= and_ln18_reg_1147_pp0_iter15_reg;
        and_ln18_reg_1147_pp0_iter17_reg <= and_ln18_reg_1147_pp0_iter16_reg;
        and_ln18_reg_1147_pp0_iter18_reg <= and_ln18_reg_1147_pp0_iter17_reg;
        and_ln18_reg_1147_pp0_iter19_reg <= and_ln18_reg_1147_pp0_iter18_reg;
        and_ln18_reg_1147_pp0_iter20_reg <= and_ln18_reg_1147_pp0_iter19_reg;
        and_ln18_reg_1147_pp0_iter21_reg <= and_ln18_reg_1147_pp0_iter20_reg;
        and_ln18_reg_1147_pp0_iter22_reg <= and_ln18_reg_1147_pp0_iter21_reg;
        and_ln18_reg_1147_pp0_iter23_reg <= and_ln18_reg_1147_pp0_iter22_reg;
        and_ln18_reg_1147_pp0_iter24_reg <= and_ln18_reg_1147_pp0_iter23_reg;
        and_ln18_reg_1147_pp0_iter25_reg <= and_ln18_reg_1147_pp0_iter24_reg;
        and_ln18_reg_1147_pp0_iter26_reg <= and_ln18_reg_1147_pp0_iter25_reg;
        and_ln18_reg_1147_pp0_iter27_reg <= and_ln18_reg_1147_pp0_iter26_reg;
        and_ln18_reg_1147_pp0_iter28_reg <= and_ln18_reg_1147_pp0_iter27_reg;
        and_ln18_reg_1147_pp0_iter2_reg <= and_ln18_reg_1147_pp0_iter1_reg;
        and_ln18_reg_1147_pp0_iter3_reg <= and_ln18_reg_1147_pp0_iter2_reg;
        and_ln18_reg_1147_pp0_iter4_reg <= and_ln18_reg_1147_pp0_iter3_reg;
        and_ln18_reg_1147_pp0_iter5_reg <= and_ln18_reg_1147_pp0_iter4_reg;
        and_ln18_reg_1147_pp0_iter6_reg <= and_ln18_reg_1147_pp0_iter5_reg;
        and_ln18_reg_1147_pp0_iter7_reg <= and_ln18_reg_1147_pp0_iter6_reg;
        and_ln18_reg_1147_pp0_iter8_reg <= and_ln18_reg_1147_pp0_iter7_reg;
        and_ln18_reg_1147_pp0_iter9_reg <= and_ln18_reg_1147_pp0_iter8_reg;
        and_ln209_reg_1140_pp0_iter10_reg <= and_ln209_reg_1140_pp0_iter9_reg;
        and_ln209_reg_1140_pp0_iter11_reg <= and_ln209_reg_1140_pp0_iter10_reg;
        and_ln209_reg_1140_pp0_iter12_reg <= and_ln209_reg_1140_pp0_iter11_reg;
        and_ln209_reg_1140_pp0_iter13_reg <= and_ln209_reg_1140_pp0_iter12_reg;
        and_ln209_reg_1140_pp0_iter14_reg <= and_ln209_reg_1140_pp0_iter13_reg;
        and_ln209_reg_1140_pp0_iter15_reg <= and_ln209_reg_1140_pp0_iter14_reg;
        and_ln209_reg_1140_pp0_iter16_reg <= and_ln209_reg_1140_pp0_iter15_reg;
        and_ln209_reg_1140_pp0_iter17_reg <= and_ln209_reg_1140_pp0_iter16_reg;
        and_ln209_reg_1140_pp0_iter18_reg <= and_ln209_reg_1140_pp0_iter17_reg;
        and_ln209_reg_1140_pp0_iter19_reg <= and_ln209_reg_1140_pp0_iter18_reg;
        and_ln209_reg_1140_pp0_iter20_reg <= and_ln209_reg_1140_pp0_iter19_reg;
        and_ln209_reg_1140_pp0_iter21_reg <= and_ln209_reg_1140_pp0_iter20_reg;
        and_ln209_reg_1140_pp0_iter22_reg <= and_ln209_reg_1140_pp0_iter21_reg;
        and_ln209_reg_1140_pp0_iter23_reg <= and_ln209_reg_1140_pp0_iter22_reg;
        and_ln209_reg_1140_pp0_iter24_reg <= and_ln209_reg_1140_pp0_iter23_reg;
        and_ln209_reg_1140_pp0_iter25_reg <= and_ln209_reg_1140_pp0_iter24_reg;
        and_ln209_reg_1140_pp0_iter26_reg <= and_ln209_reg_1140_pp0_iter25_reg;
        and_ln209_reg_1140_pp0_iter27_reg <= and_ln209_reg_1140_pp0_iter26_reg;
        and_ln209_reg_1140_pp0_iter28_reg <= and_ln209_reg_1140_pp0_iter27_reg;
        and_ln209_reg_1140_pp0_iter2_reg <= and_ln209_reg_1140_pp0_iter1_reg;
        and_ln209_reg_1140_pp0_iter3_reg <= and_ln209_reg_1140_pp0_iter2_reg;
        and_ln209_reg_1140_pp0_iter4_reg <= and_ln209_reg_1140_pp0_iter3_reg;
        and_ln209_reg_1140_pp0_iter5_reg <= and_ln209_reg_1140_pp0_iter4_reg;
        and_ln209_reg_1140_pp0_iter6_reg <= and_ln209_reg_1140_pp0_iter5_reg;
        and_ln209_reg_1140_pp0_iter7_reg <= and_ln209_reg_1140_pp0_iter6_reg;
        and_ln209_reg_1140_pp0_iter8_reg <= and_ln209_reg_1140_pp0_iter7_reg;
        and_ln209_reg_1140_pp0_iter9_reg <= and_ln209_reg_1140_pp0_iter8_reg;
        exp_Z1P_m_1_V_reg_1325 <= {{exp_Z1P_m_1_l_V_fu_796_p2[51:2]}};
        exp_Z1_V_reg_1320 <= table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0;
        exp_Z1_V_reg_1320_pp0_iter23_reg <= exp_Z1_V_reg_1320;
        exp_Z1_V_reg_1320_pp0_iter24_reg <= exp_Z1_V_reg_1320_pp0_iter23_reg;
        exp_Z1_V_reg_1320_pp0_iter25_reg <= exp_Z1_V_reg_1320_pp0_iter24_reg;
        exp_Z1_V_reg_1320_pp0_iter26_reg <= exp_Z1_V_reg_1320_pp0_iter25_reg;
        exp_Z1_V_reg_1320_pp0_iter27_reg <= exp_Z1_V_reg_1320_pp0_iter26_reg;
        exp_Z1_hi_V_reg_1330 <= {{table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_q0[57:8]}};
        exp_Z2P_m_1_V_reg_1288 <= exp_Z2P_m_1_V_fu_719_p2;
        exp_Z2P_m_1_V_reg_1288_pp0_iter17_reg <= exp_Z2P_m_1_V_reg_1288;
        exp_Z2P_m_1_V_reg_1288_pp0_iter18_reg <= exp_Z2P_m_1_V_reg_1288_pp0_iter17_reg;
        exp_Z2P_m_1_V_reg_1288_pp0_iter19_reg <= exp_Z2P_m_1_V_reg_1288_pp0_iter18_reg;
        exp_Z2P_m_1_V_reg_1288_pp0_iter20_reg <= exp_Z2P_m_1_V_reg_1288_pp0_iter19_reg;
        exp_Z2P_m_1_V_reg_1288_pp0_iter21_reg <= exp_Z2P_m_1_V_reg_1288_pp0_iter20_reg;
        icmp_ln338_1_reg_1193_pp0_iter10_reg <= icmp_ln338_1_reg_1193_pp0_iter9_reg;
        icmp_ln338_1_reg_1193_pp0_iter11_reg <= icmp_ln338_1_reg_1193_pp0_iter10_reg;
        icmp_ln338_1_reg_1193_pp0_iter12_reg <= icmp_ln338_1_reg_1193_pp0_iter11_reg;
        icmp_ln338_1_reg_1193_pp0_iter13_reg <= icmp_ln338_1_reg_1193_pp0_iter12_reg;
        icmp_ln338_1_reg_1193_pp0_iter14_reg <= icmp_ln338_1_reg_1193_pp0_iter13_reg;
        icmp_ln338_1_reg_1193_pp0_iter15_reg <= icmp_ln338_1_reg_1193_pp0_iter14_reg;
        icmp_ln338_1_reg_1193_pp0_iter16_reg <= icmp_ln338_1_reg_1193_pp0_iter15_reg;
        icmp_ln338_1_reg_1193_pp0_iter17_reg <= icmp_ln338_1_reg_1193_pp0_iter16_reg;
        icmp_ln338_1_reg_1193_pp0_iter18_reg <= icmp_ln338_1_reg_1193_pp0_iter17_reg;
        icmp_ln338_1_reg_1193_pp0_iter19_reg <= icmp_ln338_1_reg_1193_pp0_iter18_reg;
        icmp_ln338_1_reg_1193_pp0_iter20_reg <= icmp_ln338_1_reg_1193_pp0_iter19_reg;
        icmp_ln338_1_reg_1193_pp0_iter21_reg <= icmp_ln338_1_reg_1193_pp0_iter20_reg;
        icmp_ln338_1_reg_1193_pp0_iter22_reg <= icmp_ln338_1_reg_1193_pp0_iter21_reg;
        icmp_ln338_1_reg_1193_pp0_iter23_reg <= icmp_ln338_1_reg_1193_pp0_iter22_reg;
        icmp_ln338_1_reg_1193_pp0_iter24_reg <= icmp_ln338_1_reg_1193_pp0_iter23_reg;
        icmp_ln338_1_reg_1193_pp0_iter25_reg <= icmp_ln338_1_reg_1193_pp0_iter24_reg;
        icmp_ln338_1_reg_1193_pp0_iter26_reg <= icmp_ln338_1_reg_1193_pp0_iter25_reg;
        icmp_ln338_1_reg_1193_pp0_iter27_reg <= icmp_ln338_1_reg_1193_pp0_iter26_reg;
        icmp_ln338_1_reg_1193_pp0_iter28_reg <= icmp_ln338_1_reg_1193_pp0_iter27_reg;
        icmp_ln338_1_reg_1193_pp0_iter2_reg <= icmp_ln338_1_reg_1193;
        icmp_ln338_1_reg_1193_pp0_iter3_reg <= icmp_ln338_1_reg_1193_pp0_iter2_reg;
        icmp_ln338_1_reg_1193_pp0_iter4_reg <= icmp_ln338_1_reg_1193_pp0_iter3_reg;
        icmp_ln338_1_reg_1193_pp0_iter5_reg <= icmp_ln338_1_reg_1193_pp0_iter4_reg;
        icmp_ln338_1_reg_1193_pp0_iter6_reg <= icmp_ln338_1_reg_1193_pp0_iter5_reg;
        icmp_ln338_1_reg_1193_pp0_iter7_reg <= icmp_ln338_1_reg_1193_pp0_iter6_reg;
        icmp_ln338_1_reg_1193_pp0_iter8_reg <= icmp_ln338_1_reg_1193_pp0_iter7_reg;
        icmp_ln338_1_reg_1193_pp0_iter9_reg <= icmp_ln338_1_reg_1193_pp0_iter8_reg;
        icmp_ln338_reg_1170_pp0_iter10_reg <= icmp_ln338_reg_1170_pp0_iter9_reg;
        icmp_ln338_reg_1170_pp0_iter11_reg <= icmp_ln338_reg_1170_pp0_iter10_reg;
        icmp_ln338_reg_1170_pp0_iter12_reg <= icmp_ln338_reg_1170_pp0_iter11_reg;
        icmp_ln338_reg_1170_pp0_iter13_reg <= icmp_ln338_reg_1170_pp0_iter12_reg;
        icmp_ln338_reg_1170_pp0_iter14_reg <= icmp_ln338_reg_1170_pp0_iter13_reg;
        icmp_ln338_reg_1170_pp0_iter15_reg <= icmp_ln338_reg_1170_pp0_iter14_reg;
        icmp_ln338_reg_1170_pp0_iter16_reg <= icmp_ln338_reg_1170_pp0_iter15_reg;
        icmp_ln338_reg_1170_pp0_iter17_reg <= icmp_ln338_reg_1170_pp0_iter16_reg;
        icmp_ln338_reg_1170_pp0_iter18_reg <= icmp_ln338_reg_1170_pp0_iter17_reg;
        icmp_ln338_reg_1170_pp0_iter19_reg <= icmp_ln338_reg_1170_pp0_iter18_reg;
        icmp_ln338_reg_1170_pp0_iter20_reg <= icmp_ln338_reg_1170_pp0_iter19_reg;
        icmp_ln338_reg_1170_pp0_iter21_reg <= icmp_ln338_reg_1170_pp0_iter20_reg;
        icmp_ln338_reg_1170_pp0_iter22_reg <= icmp_ln338_reg_1170_pp0_iter21_reg;
        icmp_ln338_reg_1170_pp0_iter23_reg <= icmp_ln338_reg_1170_pp0_iter22_reg;
        icmp_ln338_reg_1170_pp0_iter24_reg <= icmp_ln338_reg_1170_pp0_iter23_reg;
        icmp_ln338_reg_1170_pp0_iter25_reg <= icmp_ln338_reg_1170_pp0_iter24_reg;
        icmp_ln338_reg_1170_pp0_iter26_reg <= icmp_ln338_reg_1170_pp0_iter25_reg;
        icmp_ln338_reg_1170_pp0_iter27_reg <= icmp_ln338_reg_1170_pp0_iter26_reg;
        icmp_ln338_reg_1170_pp0_iter28_reg <= icmp_ln338_reg_1170_pp0_iter27_reg;
        icmp_ln338_reg_1170_pp0_iter2_reg <= icmp_ln338_reg_1170_pp0_iter1_reg;
        icmp_ln338_reg_1170_pp0_iter3_reg <= icmp_ln338_reg_1170_pp0_iter2_reg;
        icmp_ln338_reg_1170_pp0_iter4_reg <= icmp_ln338_reg_1170_pp0_iter3_reg;
        icmp_ln338_reg_1170_pp0_iter5_reg <= icmp_ln338_reg_1170_pp0_iter4_reg;
        icmp_ln338_reg_1170_pp0_iter6_reg <= icmp_ln338_reg_1170_pp0_iter5_reg;
        icmp_ln338_reg_1170_pp0_iter7_reg <= icmp_ln338_reg_1170_pp0_iter6_reg;
        icmp_ln338_reg_1170_pp0_iter8_reg <= icmp_ln338_reg_1170_pp0_iter7_reg;
        icmp_ln338_reg_1170_pp0_iter9_reg <= icmp_ln338_reg_1170_pp0_iter8_reg;
        m_diff_hi_V_reg_1220 <= {{ret_V_19_fu_586_p2[58:51]}};
        m_diff_hi_V_reg_1220_pp0_iter11_reg <= m_diff_hi_V_reg_1220;
        m_diff_hi_V_reg_1220_pp0_iter12_reg <= m_diff_hi_V_reg_1220_pp0_iter11_reg;
        m_diff_hi_V_reg_1220_pp0_iter13_reg <= m_diff_hi_V_reg_1220_pp0_iter12_reg;
        m_diff_hi_V_reg_1220_pp0_iter14_reg <= m_diff_hi_V_reg_1220_pp0_iter13_reg;
        m_diff_hi_V_reg_1220_pp0_iter15_reg <= m_diff_hi_V_reg_1220_pp0_iter14_reg;
        m_diff_hi_V_reg_1220_pp0_iter16_reg <= m_diff_hi_V_reg_1220_pp0_iter15_reg;
        m_diff_hi_V_reg_1220_pp0_iter17_reg <= m_diff_hi_V_reg_1220_pp0_iter16_reg;
        m_diff_hi_V_reg_1220_pp0_iter18_reg <= m_diff_hi_V_reg_1220_pp0_iter17_reg;
        m_diff_hi_V_reg_1220_pp0_iter19_reg <= m_diff_hi_V_reg_1220_pp0_iter18_reg;
        m_diff_hi_V_reg_1220_pp0_iter20_reg <= m_diff_hi_V_reg_1220_pp0_iter19_reg;
        p_Result_275_reg_1135_pp0_iter10_reg <= p_Result_275_reg_1135_pp0_iter9_reg;
        p_Result_275_reg_1135_pp0_iter11_reg <= p_Result_275_reg_1135_pp0_iter10_reg;
        p_Result_275_reg_1135_pp0_iter12_reg <= p_Result_275_reg_1135_pp0_iter11_reg;
        p_Result_275_reg_1135_pp0_iter13_reg <= p_Result_275_reg_1135_pp0_iter12_reg;
        p_Result_275_reg_1135_pp0_iter14_reg <= p_Result_275_reg_1135_pp0_iter13_reg;
        p_Result_275_reg_1135_pp0_iter15_reg <= p_Result_275_reg_1135_pp0_iter14_reg;
        p_Result_275_reg_1135_pp0_iter16_reg <= p_Result_275_reg_1135_pp0_iter15_reg;
        p_Result_275_reg_1135_pp0_iter17_reg <= p_Result_275_reg_1135_pp0_iter16_reg;
        p_Result_275_reg_1135_pp0_iter18_reg <= p_Result_275_reg_1135_pp0_iter17_reg;
        p_Result_275_reg_1135_pp0_iter19_reg <= p_Result_275_reg_1135_pp0_iter18_reg;
        p_Result_275_reg_1135_pp0_iter20_reg <= p_Result_275_reg_1135_pp0_iter19_reg;
        p_Result_275_reg_1135_pp0_iter21_reg <= p_Result_275_reg_1135_pp0_iter20_reg;
        p_Result_275_reg_1135_pp0_iter22_reg <= p_Result_275_reg_1135_pp0_iter21_reg;
        p_Result_275_reg_1135_pp0_iter23_reg <= p_Result_275_reg_1135_pp0_iter22_reg;
        p_Result_275_reg_1135_pp0_iter24_reg <= p_Result_275_reg_1135_pp0_iter23_reg;
        p_Result_275_reg_1135_pp0_iter25_reg <= p_Result_275_reg_1135_pp0_iter24_reg;
        p_Result_275_reg_1135_pp0_iter26_reg <= p_Result_275_reg_1135_pp0_iter25_reg;
        p_Result_275_reg_1135_pp0_iter27_reg <= p_Result_275_reg_1135_pp0_iter26_reg;
        p_Result_275_reg_1135_pp0_iter28_reg <= p_Result_275_reg_1135_pp0_iter27_reg;
        p_Result_275_reg_1135_pp0_iter2_reg <= p_Result_275_reg_1135_pp0_iter1_reg;
        p_Result_275_reg_1135_pp0_iter3_reg <= p_Result_275_reg_1135_pp0_iter2_reg;
        p_Result_275_reg_1135_pp0_iter4_reg <= p_Result_275_reg_1135_pp0_iter3_reg;
        p_Result_275_reg_1135_pp0_iter5_reg <= p_Result_275_reg_1135_pp0_iter4_reg;
        p_Result_275_reg_1135_pp0_iter6_reg <= p_Result_275_reg_1135_pp0_iter5_reg;
        p_Result_275_reg_1135_pp0_iter7_reg <= p_Result_275_reg_1135_pp0_iter6_reg;
        p_Result_275_reg_1135_pp0_iter8_reg <= p_Result_275_reg_1135_pp0_iter7_reg;
        p_Result_275_reg_1135_pp0_iter9_reg <= p_Result_275_reg_1135_pp0_iter8_reg;
        p_Result_276_reg_1183_pp0_iter2_reg <= p_Result_276_reg_1183;
        r_V_50_reg_1178_pp0_iter2_reg <= r_V_50_reg_1178;
        r_V_50_reg_1178_pp0_iter3_reg <= r_V_50_reg_1178_pp0_iter2_reg;
        r_V_50_reg_1178_pp0_iter4_reg <= r_V_50_reg_1178_pp0_iter3_reg;
        r_V_50_reg_1178_pp0_iter5_reg <= r_V_50_reg_1178_pp0_iter4_reg;
        r_V_50_reg_1178_pp0_iter6_reg <= r_V_50_reg_1178_pp0_iter5_reg;
        r_V_50_reg_1178_pp0_iter7_reg <= r_V_50_reg_1178_pp0_iter6_reg;
        r_V_50_reg_1178_pp0_iter8_reg <= r_V_50_reg_1178_pp0_iter7_reg;
        r_V_50_reg_1178_pp0_iter9_reg <= r_V_50_reg_1178_pp0_iter8_reg;
        r_V_55_reg_1345 <= grp_fu_828_p2;
        r_V_55_reg_1345_pp0_iter28_reg <= r_V_55_reg_1345;
        r_exp_V_3_reg_1203 <= r_exp_V_3_fu_545_p3;
        r_exp_V_3_reg_1203_pp0_iter10_reg <= r_exp_V_3_reg_1203_pp0_iter9_reg;
        r_exp_V_3_reg_1203_pp0_iter11_reg <= r_exp_V_3_reg_1203_pp0_iter10_reg;
        r_exp_V_3_reg_1203_pp0_iter12_reg <= r_exp_V_3_reg_1203_pp0_iter11_reg;
        r_exp_V_3_reg_1203_pp0_iter13_reg <= r_exp_V_3_reg_1203_pp0_iter12_reg;
        r_exp_V_3_reg_1203_pp0_iter14_reg <= r_exp_V_3_reg_1203_pp0_iter13_reg;
        r_exp_V_3_reg_1203_pp0_iter15_reg <= r_exp_V_3_reg_1203_pp0_iter14_reg;
        r_exp_V_3_reg_1203_pp0_iter16_reg <= r_exp_V_3_reg_1203_pp0_iter15_reg;
        r_exp_V_3_reg_1203_pp0_iter17_reg <= r_exp_V_3_reg_1203_pp0_iter16_reg;
        r_exp_V_3_reg_1203_pp0_iter18_reg <= r_exp_V_3_reg_1203_pp0_iter17_reg;
        r_exp_V_3_reg_1203_pp0_iter19_reg <= r_exp_V_3_reg_1203_pp0_iter18_reg;
        r_exp_V_3_reg_1203_pp0_iter20_reg <= r_exp_V_3_reg_1203_pp0_iter19_reg;
        r_exp_V_3_reg_1203_pp0_iter21_reg <= r_exp_V_3_reg_1203_pp0_iter20_reg;
        r_exp_V_3_reg_1203_pp0_iter22_reg <= r_exp_V_3_reg_1203_pp0_iter21_reg;
        r_exp_V_3_reg_1203_pp0_iter23_reg <= r_exp_V_3_reg_1203_pp0_iter22_reg;
        r_exp_V_3_reg_1203_pp0_iter24_reg <= r_exp_V_3_reg_1203_pp0_iter23_reg;
        r_exp_V_3_reg_1203_pp0_iter25_reg <= r_exp_V_3_reg_1203_pp0_iter24_reg;
        r_exp_V_3_reg_1203_pp0_iter26_reg <= r_exp_V_3_reg_1203_pp0_iter25_reg;
        r_exp_V_3_reg_1203_pp0_iter27_reg <= r_exp_V_3_reg_1203_pp0_iter26_reg;
        r_exp_V_3_reg_1203_pp0_iter28_reg <= r_exp_V_3_reg_1203_pp0_iter27_reg;
        r_exp_V_3_reg_1203_pp0_iter5_reg <= r_exp_V_3_reg_1203;
        r_exp_V_3_reg_1203_pp0_iter6_reg <= r_exp_V_3_reg_1203_pp0_iter5_reg;
        r_exp_V_3_reg_1203_pp0_iter7_reg <= r_exp_V_3_reg_1203_pp0_iter6_reg;
        r_exp_V_3_reg_1203_pp0_iter8_reg <= r_exp_V_3_reg_1203_pp0_iter7_reg;
        r_exp_V_3_reg_1203_pp0_iter9_reg <= r_exp_V_3_reg_1203_pp0_iter8_reg;
        ret_V_20_reg_1252 <= ret_V_20_fu_663_p2;
        ret_V_20_reg_1252_pp0_iter12_reg <= ret_V_20_reg_1252;
        ret_V_20_reg_1252_pp0_iter13_reg <= ret_V_20_reg_1252_pp0_iter12_reg;
        ret_V_20_reg_1252_pp0_iter14_reg <= ret_V_20_reg_1252_pp0_iter13_reg;
        ret_V_20_reg_1252_pp0_iter15_reg <= ret_V_20_reg_1252_pp0_iter14_reg;
        ret_V_22_reg_1351 <= ret_V_22_fu_837_p2;
        select_ln253_reg_1153_pp0_iter10_reg <= select_ln253_reg_1153_pp0_iter9_reg;
        select_ln253_reg_1153_pp0_iter11_reg <= select_ln253_reg_1153_pp0_iter10_reg;
        select_ln253_reg_1153_pp0_iter12_reg <= select_ln253_reg_1153_pp0_iter11_reg;
        select_ln253_reg_1153_pp0_iter13_reg <= select_ln253_reg_1153_pp0_iter12_reg;
        select_ln253_reg_1153_pp0_iter14_reg <= select_ln253_reg_1153_pp0_iter13_reg;
        select_ln253_reg_1153_pp0_iter15_reg <= select_ln253_reg_1153_pp0_iter14_reg;
        select_ln253_reg_1153_pp0_iter16_reg <= select_ln253_reg_1153_pp0_iter15_reg;
        select_ln253_reg_1153_pp0_iter17_reg <= select_ln253_reg_1153_pp0_iter16_reg;
        select_ln253_reg_1153_pp0_iter18_reg <= select_ln253_reg_1153_pp0_iter17_reg;
        select_ln253_reg_1153_pp0_iter19_reg <= select_ln253_reg_1153_pp0_iter18_reg;
        select_ln253_reg_1153_pp0_iter20_reg <= select_ln253_reg_1153_pp0_iter19_reg;
        select_ln253_reg_1153_pp0_iter21_reg <= select_ln253_reg_1153_pp0_iter20_reg;
        select_ln253_reg_1153_pp0_iter22_reg <= select_ln253_reg_1153_pp0_iter21_reg;
        select_ln253_reg_1153_pp0_iter23_reg <= select_ln253_reg_1153_pp0_iter22_reg;
        select_ln253_reg_1153_pp0_iter24_reg <= select_ln253_reg_1153_pp0_iter23_reg;
        select_ln253_reg_1153_pp0_iter25_reg <= select_ln253_reg_1153_pp0_iter24_reg;
        select_ln253_reg_1153_pp0_iter26_reg <= select_ln253_reg_1153_pp0_iter25_reg;
        select_ln253_reg_1153_pp0_iter27_reg <= select_ln253_reg_1153_pp0_iter26_reg;
        select_ln253_reg_1153_pp0_iter28_reg <= select_ln253_reg_1153_pp0_iter27_reg;
        select_ln253_reg_1153_pp0_iter2_reg <= select_ln253_reg_1153_pp0_iter1_reg;
        select_ln253_reg_1153_pp0_iter3_reg <= select_ln253_reg_1153_pp0_iter2_reg;
        select_ln253_reg_1153_pp0_iter4_reg <= select_ln253_reg_1153_pp0_iter3_reg;
        select_ln253_reg_1153_pp0_iter5_reg <= select_ln253_reg_1153_pp0_iter4_reg;
        select_ln253_reg_1153_pp0_iter6_reg <= select_ln253_reg_1153_pp0_iter5_reg;
        select_ln253_reg_1153_pp0_iter7_reg <= select_ln253_reg_1153_pp0_iter6_reg;
        select_ln253_reg_1153_pp0_iter8_reg <= select_ln253_reg_1153_pp0_iter7_reg;
        select_ln253_reg_1153_pp0_iter9_reg <= select_ln253_reg_1153_pp0_iter8_reg;
        tmp_436_reg_1356 <= add_ln1146_1_fu_858_p2[32'd106];
        tmp_76_reg_1278 <= {{grp_fu_684_p2[78:59]}};
        tmp_77_reg_1294 <= {{table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0[41:2]}};
        tmp_77_reg_1294_pp0_iter17_reg <= tmp_77_reg_1294;
        tmp_77_reg_1294_pp0_iter18_reg <= tmp_77_reg_1294_pp0_iter17_reg;
        tmp_77_reg_1294_pp0_iter19_reg <= tmp_77_reg_1294_pp0_iter18_reg;
        tmp_77_reg_1294_pp0_iter20_reg <= tmp_77_reg_1294_pp0_iter19_reg;
        tmp_77_reg_1294_pp0_iter21_reg <= tmp_77_reg_1294_pp0_iter20_reg;
        tmp_78_reg_1315 <= {{grp_fu_750_p2[92:57]}};
        tmp_i_reg_1263[25 : 0] <= tmp_i_fu_669_p4[25 : 0];
tmp_i_reg_1263[42 : 35] <= tmp_i_fu_669_p4[42 : 35];
        tmp_i_reg_1263_pp0_iter13_reg[25 : 0] <= tmp_i_reg_1263[25 : 0];
tmp_i_reg_1263_pp0_iter13_reg[42 : 35] <= tmp_i_reg_1263[42 : 35];
        tmp_i_reg_1263_pp0_iter14_reg[25 : 0] <= tmp_i_reg_1263_pp0_iter13_reg[25 : 0];
tmp_i_reg_1263_pp0_iter14_reg[42 : 35] <= tmp_i_reg_1263_pp0_iter13_reg[42 : 35];
        tmp_i_reg_1263_pp0_iter15_reg[25 : 0] <= tmp_i_reg_1263_pp0_iter14_reg[25 : 0];
tmp_i_reg_1263_pp0_iter15_reg[42 : 35] <= tmp_i_reg_1263_pp0_iter14_reg[42 : 35];
        tmp_s_reg_1215 <= {{grp_fu_556_p2[83:13]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln18_reg_1147 <= and_ln18_fu_311_p2;
        and_ln18_reg_1147_pp0_iter1_reg <= and_ln18_reg_1147;
        and_ln209_reg_1140 <= and_ln209_fu_299_p2;
        and_ln209_reg_1140_pp0_iter1_reg <= and_ln209_reg_1140;
        icmp_ln338_1_reg_1193 <= icmp_ln338_1_fu_489_p2;
        icmp_ln338_reg_1170 <= icmp_ln338_fu_375_p2;
        icmp_ln338_reg_1170_pp0_iter1_reg <= icmp_ln338_reg_1170;
        isNeg_reg_1159 <= m_exp_fu_321_p2[32'd11];
        m_exp_2_reg_1165 <= m_exp_2_fu_367_p3;
        p_Result_275_reg_1135 <= p_Val2_s_fu_261_p1[32'd63];
        p_Result_275_reg_1135_pp0_iter1_reg <= p_Result_275_reg_1135;
        p_Result_276_reg_1183 <= r_V_50_fu_419_p3[32'd70];
        r_V_50_reg_1178 <= r_V_50_fu_419_p3;
        select_ln253_reg_1153 <= select_ln253_fu_341_p3;
        select_ln253_reg_1153_pp0_iter1_reg <= select_ln253_reg_1153;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_251_reg_1258 <= table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q1;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter29 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0))) begin
        ap_idle_pp0_0to28 = 1'b1;
    end else begin
        ap_idle_pp0_0to28 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to28 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_1124_ce = 1'b1;
    end else begin
        grp_fu_1124_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_556_ce = 1'b1;
    end else begin
        grp_fu_556_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_684_ce = 1'b1;
    end else begin
        grp_fu_684_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_750_ce = 1'b1;
    end else begin
        grp_fu_750_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_828_ce = 1'b1;
    end else begin
        grp_fu_828_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b1;
    end else begin
        table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b1;
    end else begin
        table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b1;
    end else begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1 = 1'b1;
    end else begin
        table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Z3_V_fu_612_p4 = {{ret_V_19_fu_586_p2[42:35]}};

assign Z4_V_fu_622_p1 = ret_V_19_fu_586_p2[34:0];

assign Z4_ind_V_fu_626_p4 = {{ret_V_19_fu_586_p2[34:27]}};

assign add_ln1146_1_fu_858_p2 = (trunc_ln_fu_850_p3 + zext_ln1146_fu_843_p1);

assign add_ln657_2_fu_787_p2 = (zext_ln657_2_fu_784_p1 + exp_Z2P_m_1_V_reg_1288_pp0_iter21_reg);

assign add_ln657_fu_710_p2 = (zext_ln657_fu_707_p1 + ret_V_20_reg_1252_pp0_iter15_reg);

assign add_ln805_fu_531_p2 = (13'd1 + tmp_16_fu_506_p4);

assign and_ln18_fu_311_p2 = (icmp_ln833_fu_287_p2 & icmp_ln833_3_fu_305_p2);

assign and_ln209_fu_299_p2 = (icmp_ln837_fu_293_p2 & icmp_ln833_fu_287_p2);

assign and_ln338_1_fu_1082_p2 = (xor_ln338_1_fu_1076_p2 & icmp_ln338_reg_1170_pp0_iter28_reg);

assign and_ln338_fu_1032_p2 = (or_ln338_fu_949_p2 & icmp_ln338_reg_1170_pp0_iter28_reg);

assign and_ln849_fu_1042_p2 = (xor_ln338_fu_1037_p2 & icmp_ln849_fu_943_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_start == 1'b1)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = ((sel_tmp16_fu_1110_p2[0:0] === 1'b1) ? 64'd0 : select_ln214_2_fu_1068_p3);

assign bitcast_ln512_fu_1022_p1 = p_Result_277_fu_1012_p4;

assign e_frac_V_fu_335_p2 = (54'd0 - p_Result_s_fu_327_p3);

assign exp_Z1P_m_1_l_V_fu_796_p2 = (zext_ln682_fu_780_p1 + zext_ln657_3_fu_792_p1);

assign exp_Z2P_m_1_V_fu_719_p2 = (ret_V_21_fu_704_p1 + zext_ln657_1_fu_715_p1);

assign f_Z4_V_fu_646_p4 = {{table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_q0[25:16]}};

assign grp_fu_1124_p0 = 31'd23637;

assign grp_fu_556_p0 = 84'd1636647506585939924452;

assign grp_fu_684_p0 = grp_fu_684_p00;

assign grp_fu_684_p00 = ret_V_20_reg_1252;

assign grp_fu_684_p1 = grp_fu_684_p10;

assign grp_fu_684_p10 = tmp_i_fu_669_p4;

assign grp_fu_750_p0 = grp_fu_750_p00;

assign grp_fu_750_p00 = exp_Z2P_m_1_V_reg_1288;

assign grp_fu_750_p1 = grp_fu_750_p10;

assign grp_fu_750_p10 = lshr_ln662_6_fu_735_p4;

assign grp_fu_828_p0 = grp_fu_828_p00;

assign grp_fu_828_p00 = exp_Z1P_m_1_V_reg_1325;

assign grp_fu_828_p1 = grp_fu_828_p10;

assign grp_fu_828_p10 = exp_Z1_hi_V_reg_1330;

assign icmp_ln338_1_fu_489_p2 = ((shl_ln_fu_481_p3 != sext_ln682_fu_388_p1) ? 1'b1 : 1'b0);

assign icmp_ln338_fu_375_p2 = (($signed(m_exp_fu_321_p2) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln805_fu_525_p2 = ((trunc_ln805_fu_522_p1 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln833_3_fu_305_p2 = ((tmp_V_49_fu_283_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln833_fu_287_p2 = ((tmp_V_fu_273_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln837_fu_293_p2 = ((tmp_V_49_fu_283_p1 != 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln849_fu_943_p2 = (($signed(tmp_437_fu_933_p4) > $signed(3'd0)) ? 1'b1 : 1'b0);

assign icmp_ln853_fu_969_p2 = (($signed(r_exp_V_2_fu_927_p3) < $signed(13'd7170)) ? 1'b1 : 1'b0);

assign isNeg_fu_349_p3 = m_exp_fu_321_p2[32'd11];

assign lhs_V_15_fu_656_p1 = Z4_V_reg_1237;

assign lhs_V_16_fu_834_p1 = exp_Z1_V_reg_1320_pp0_iter27_reg;

assign lhs_V_4_fu_770_p5 = {{{{Z2_V_reg_1225_pp0_iter21_reg}, {1'd0}}, {tmp_77_reg_1294_pp0_iter21_reg}}, {2'd0}};

assign lhs_V_6_fu_906_p3 = {{ret_V_22_reg_1351}, {49'd0}};

assign lhs_V_fu_572_p1 = r_V_50_reg_1178_pp0_iter9_reg;

assign lshr_ln662_6_fu_735_p4 = {{{Z2_V_reg_1225_pp0_iter16_reg}, {1'd0}}, {tmp_77_reg_1294}};

assign m_exp_2_fu_367_p3 = ((isNeg_fu_349_p3[0:0] === 1'b1) ? sext_ln1311_fu_363_p1 : m_exp_fu_321_p2);

assign m_exp_fu_321_p2 = ($signed(12'd3073) + $signed(zext_ln502_fu_317_p1));

assign m_fix_hi_V_fu_452_p4 = {{r_V_50_fu_419_p3[70:55]}};

assign m_fix_l_V_fu_426_p4 = {{r_V_50_fu_419_p3[70:7]}};

assign m_frac_l_V_fu_381_p3 = {{select_ln253_reg_1153}, {7'd0}};

assign or_ln214_1_fu_894_p2 = (and_ln209_reg_1140_pp0_iter28_reg | and_ln18_reg_1147_pp0_iter28_reg);

assign or_ln214_fu_882_p2 = (x_is_pinf_fu_877_p2 | and_ln209_reg_1140_pp0_iter28_reg);

assign or_ln338_fu_949_p2 = (icmp_ln849_fu_943_p2 | icmp_ln338_1_reg_1193_pp0_iter28_reg);

assign or_ln849_1_fu_1087_p2 = (icmp_ln849_fu_943_p2 | icmp_ln338_reg_1170_pp0_iter28_reg);

assign or_ln849_2_fu_1098_p2 = (xor_ln849_fu_1092_p2 | and_ln338_1_fu_1082_p2);

assign or_ln849_fu_1048_p2 = (and_ln849_fu_1042_p2 | and_ln338_fu_1032_p2);

assign out_exp_V_fu_1006_p2 = (11'd1023 + trunc_ln168_fu_1002_p1);

assign p_Result_268_fu_515_p3 = grp_fu_1124_p3[32'd30];

assign p_Result_275_fu_265_p3 = p_Val2_s_fu_261_p1[32'd63];

assign p_Result_277_fu_1012_p4 = {{{{1'd0}, {out_exp_V_fu_1006_p2}}}, {tmp_V_50_fu_995_p3}};

assign p_Result_s_fu_327_p3 = {{2'd1}, {tmp_V_49_fu_283_p1}};

assign p_Val2_s_fu_261_p1 = x;

assign r_V_38_fu_413_p2 = sext_ln682_fu_388_p1 << zext_ln1287_fu_395_p1;

assign r_V_40_fu_440_p2 = m_fix_l_V_fu_426_p4 << zext_ln1253_fu_436_p1;

assign r_V_41_fu_446_p2 = $signed(m_fix_l_V_fu_426_p4) >>> zext_ln1253_fu_436_p1;

assign r_V_50_fu_419_p3 = ((isNeg_reg_1159[0:0] === 1'b1) ? sext_ln1287_fu_409_p1 : r_V_38_fu_413_p2);

assign r_V_fu_403_p2 = $signed(m_frac_l_V_fu_381_p3) >>> zext_ln1285_fu_399_p1;

assign r_exp_V_2_fu_927_p3 = ((tmp_436_reg_1356[0:0] === 1'b1) ? r_exp_V_3_reg_1203_pp0_iter28_reg : r_exp_V_fu_922_p2);

assign r_exp_V_3_fu_545_p3 = ((p_Result_268_fu_515_p3[0:0] === 1'b1) ? select_ln805_fu_537_p3 : tmp_16_fu_506_p4);

assign r_exp_V_fu_922_p2 = ($signed(13'd8191) + $signed(r_exp_V_3_reg_1203_pp0_iter28_reg));

assign ret_V_19_fu_586_p2 = ($signed(lhs_V_fu_572_p1) - $signed(sext_ln682_2_fu_582_p1));

assign ret_V_20_fu_663_p2 = (rhs_V_5_fu_659_p1 + lhs_V_15_fu_656_p1);

assign ret_V_21_fu_704_p1 = tmp_i_reg_1263_pp0_iter15_reg;

assign ret_V_22_fu_837_p2 = (59'd16 + lhs_V_16_fu_834_p1);

assign ret_V_23_fu_916_p2 = (zext_ln657_5_fu_913_p1 + lhs_V_6_fu_906_p3);

assign rhs_V_1_fu_575_p3 = {{tmp_s_reg_1215}, {1'd0}};

assign rhs_V_5_fu_659_p1 = f_Z4_V_fu_646_p4;

assign rhs_V_fu_495_p3 = {{p_Result_276_reg_1183_pp0_iter2_reg}, {18'd131072}};

assign sel_tmp16_fu_1110_p2 = (tmp19_fu_1104_p2 & icmp_ln853_fu_969_p2);

assign sel_tmp5_fu_1054_p2 = (xor_ln214_fu_1026_p2 & or_ln849_fu_1048_p2);

assign sel_tmp6_fu_1060_p3 = ((sel_tmp5_fu_1054_p2[0:0] === 1'b1) ? select_ln339_fu_961_p3 : bitcast_ln512_fu_1022_p1);

assign select_ln1322_fu_474_p3 = ((isNeg_reg_1159[0:0] === 1'b1) ? r_V_40_fu_440_p2 : r_V_41_fu_446_p2);

assign select_ln214_1_fu_898_p3 = ((or_ln214_fu_882_p2[0:0] === 1'b1) ? select_ln214_fu_887_p3 : 64'd0);

assign select_ln214_2_fu_1068_p3 = ((or_ln214_1_fu_894_p2[0:0] === 1'b1) ? select_ln214_1_fu_898_p3 : sel_tmp6_fu_1060_p3);

assign select_ln214_fu_887_p3 = ((and_ln209_reg_1140_pp0_iter28_reg[0:0] === 1'b1) ? 64'd9223372036854775807 : 64'd9218868437227405312);

assign select_ln253_fu_341_p3 = ((p_Result_275_fu_265_p3[0:0] === 1'b1) ? e_frac_V_fu_335_p2 : p_Result_s_fu_327_p3);

assign select_ln339_fu_961_p3 = ((tmp_438_fu_954_p3[0:0] === 1'b1) ? 64'd0 : 64'd9218868437227405312);

assign select_ln805_fu_537_p3 = ((icmp_ln805_fu_525_p2[0:0] === 1'b1) ? tmp_16_fu_506_p4 : add_ln805_fu_531_p2);

assign sext_ln1287_fu_409_p1 = $signed(r_V_fu_403_p2);

assign sext_ln1311_1_fu_392_p1 = $signed(m_exp_2_reg_1165);

assign sext_ln1311_fu_363_p1 = $signed(sub_ln1311_fu_357_p2);

assign sext_ln682_2_fu_582_p1 = $signed(rhs_V_1_fu_575_p3);

assign sext_ln682_fu_388_p1 = m_frac_l_V_fu_381_p3;

assign shl_ln_fu_481_p3 = {{select_ln1322_fu_474_p3}, {7'd0}};

assign sub_ln1311_fu_357_p2 = (11'd1023 - tmp_V_fu_273_p4);

assign table_exp_Z1_ap_ufixed_58_1_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 = zext_ln498_fu_756_p1;

assign table_f_Z2_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 = zext_ln498_3_fu_700_p1;

assign table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address0 = zext_ln498_1_fu_636_p1;

assign table_f_Z3_ap_ufixed_59_0_ap_q_mode_5_ap_o_mode_3_0_array_V_address1 = zext_ln498_2_fu_641_p1;

assign tmp19_fu_1104_p2 = (xor_ln214_fu_1026_p2 & or_ln849_2_fu_1098_p2);

assign tmp_16_fu_506_p4 = {{grp_fu_1124_p3[30:18]}};

assign tmp_17_fu_985_p4 = {{ret_V_23_fu_916_p2[104:53]}};

assign tmp_437_fu_933_p4 = {{r_exp_V_2_fu_927_p3[12:10]}};

assign tmp_438_fu_954_p3 = select_ln253_reg_1153_pp0_iter28_reg[32'd53];

assign tmp_V_49_fu_283_p1 = p_Val2_s_fu_261_p1[51:0];

assign tmp_V_50_fu_995_p3 = ((tmp_436_reg_1356[0:0] === 1'b1) ? tmp_fu_975_p4 : tmp_17_fu_985_p4);

assign tmp_V_fu_273_p4 = {{p_Val2_s_fu_261_p1[62:52]}};

assign tmp_fu_975_p4 = {{ret_V_23_fu_916_p2[105:54]}};

assign tmp_i_fu_669_p4 = {{{Z3_V_reg_1232_pp0_iter11_reg}, {9'd0}}, {p_Val2_251_reg_1258}};

assign trunc_ln1146_fu_846_p1 = ret_V_22_fu_837_p2[57:0];

assign trunc_ln168_fu_1002_p1 = r_exp_V_2_fu_927_p3[10:0];

assign trunc_ln805_fu_522_p1 = grp_fu_1124_p3[17:0];

assign trunc_ln_fu_850_p3 = {{trunc_ln1146_fu_846_p1}, {49'd0}};

assign x_is_pinf_fu_877_p2 = (xor_ln936_fu_872_p2 & and_ln18_reg_1147_pp0_iter28_reg);

assign xor_ln214_fu_1026_p2 = (or_ln214_1_fu_894_p2 ^ 1'd1);

assign xor_ln338_1_fu_1076_p2 = (or_ln338_fu_949_p2 ^ 1'd1);

assign xor_ln338_fu_1037_p2 = (icmp_ln338_reg_1170_pp0_iter28_reg ^ 1'd1);

assign xor_ln849_fu_1092_p2 = (or_ln849_1_fu_1087_p2 ^ 1'd1);

assign xor_ln936_fu_872_p2 = (p_Result_275_reg_1135_pp0_iter28_reg ^ 1'd1);

assign zext_ln1146_fu_843_p1 = r_V_55_reg_1345;

assign zext_ln1253_fu_436_p1 = $unsigned(sext_ln1311_1_fu_392_p1);

assign zext_ln1285_fu_399_p1 = $unsigned(sext_ln1311_1_fu_392_p1);

assign zext_ln1287_fu_395_p1 = $unsigned(sext_ln1311_1_fu_392_p1);

assign zext_ln498_1_fu_636_p1 = Z4_ind_V_fu_626_p4;

assign zext_ln498_2_fu_641_p1 = Z3_V_fu_612_p4;

assign zext_ln498_3_fu_700_p1 = Z2_V_reg_1225_pp0_iter14_reg;

assign zext_ln498_fu_756_p1 = m_diff_hi_V_reg_1220_pp0_iter20_reg;

assign zext_ln502_fu_317_p1 = tmp_V_fu_273_p4;

assign zext_ln657_1_fu_715_p1 = add_ln657_fu_710_p2;

assign zext_ln657_2_fu_784_p1 = tmp_78_reg_1315;

assign zext_ln657_3_fu_792_p1 = add_ln657_2_fu_787_p2;

assign zext_ln657_5_fu_913_p1 = r_V_55_reg_1345_pp0_iter28_reg;

assign zext_ln657_fu_707_p1 = tmp_76_reg_1278;

assign zext_ln682_fu_780_p1 = lhs_V_4_fu_770_p5;

always @ (posedge ap_clk) begin
    tmp_i_reg_1263[34:26] <= 9'b000000000;
    tmp_i_reg_1263_pp0_iter13_reg[34:26] <= 9'b000000000;
    tmp_i_reg_1263_pp0_iter14_reg[34:26] <= 9'b000000000;
    tmp_i_reg_1263_pp0_iter15_reg[34:26] <= 9'b000000000;
end

endmodule //kerneldl_exp_generic_double_s
