catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# Hls run script generated by the compiler
# 

set xocc_optimize_level 0
open_project kerneldl
set_top kerneldl
add_files "/home/inaba/alveo/DanQ_fhalf/src/kernel/kernel.cpp" -cflags " -I /home/inaba/alveo/DanQ_fhalf/src/kernel "
open_solution solution
set_part xcu200-fsgd2104-2-e
create_clock -period 300MHz -name default
config_sdx -target xocc
config_export -vivado_optimization_level $xocc_optimize_level
config_dataflow -strict_mode warning
set_clock_uncertainty 27.000000%
config_interface -m_axi_addr64
config_export -format ip_catalog -ipname kerneldl
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
