#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1_AR73068_op (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Sat Jan 02 14:58:47 UTC 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail

xv_cxl_lib_path="/opt/Xilinx/Vivado/2019.1.op2552052/data/xsim"
xv_cpt_lib_path=""
xv_ext_lib_path=""
xv_boost_lib_path="/opt/Xilinx/Vivado/2019.1.op2552052/tps/boost_1_64_0"

echo "xvlog --incr --relax -prj emu_wrapper_vlog.prj"
xvlog --incr --relax -prj emu_wrapper_vlog.prj 2>&1 | tee compile.log

echo "xvhdl --incr --relax -prj emu_wrapper_vhdl.prj"
xvhdl --incr --relax -prj emu_wrapper_vhdl.prj 2>&1 | tee -a compile.log

echo "xsc -c --gcc_compile_options "-DBOOST_SYSTEM_NO_DEPRECATED" --gcc_compile_options "-I/opt/Xilinx/Vivado/2019.1.op2552052/data/simmodels/xsim/2019.1/lnx64/6.2.0/ext/protobuf/include" --gcc_compile_options "-I../../../../prj.ip_user_files/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_0_0/sysc -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_0_0/sim -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_1_0/sysc -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_1_0/sim -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_2_0/sysc -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_2_0/sim -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_3_0/sysc -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_3_0/sim -I$xv_boost_lib_path" -work xil_defaultlib -f emu_wrapper_xsc.prj"
xsc -c --gcc_compile_options "-DBOOST_SYSTEM_NO_DEPRECATED" --gcc_compile_options "-I/opt/Xilinx/Vivado/2019.1.op2552052/data/simmodels/xsim/2019.1/lnx64/6.2.0/ext/protobuf/include" --gcc_compile_options "-I../../../../prj.ip_user_files/bd/emu/ip/emu_sdaccel_generic_pcie_0_0/sim_tlm -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_0_0/sysc -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_0_0/sim -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_1_0/sysc -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_1_0/sim -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_2_0/sysc -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_2_0/sim -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_3_0/sysc -I../../../../prj.ip_user_files/bd/emu/ip/emu_sim_axi_perf_mon_3_0/sim -I$xv_boost_lib_path" -work xil_defaultlib -f emu_wrapper_xsc.prj 2>&1 | tee -a compile.log

